export const uiTranslations = {
  soldOut: "Agotado",
  popular: "Popular",
  new: "Nuevo",
  recommended: "Recomendado",
  others: "Otros",
  emptyMenu: "El menú aún no tiene productos disponibles.",
  createdWith: "Menú digital creado con",
  searchPlaceholder: "Buscar plato o bebida...",
  // Landing
  slogan: "La revolución del menú digital en Panamá",
  title1: "Tu menú digital,",
  title2: "siempre actualizado.",
  subtitle: "Crea un menú QR moderno en minutos. Cambia precios, platos y disponibilidad desde tu celular, sin imprimir nada.",
  registerBtn: "Registrar mi restaurante",
  loginBtn: "Entrar al Panel",
  feature1Title: "Cero impresión",
  feature1Desc: "Ahorra costos y ayuda al planeta con un menú 100% digital.",
  feature2Title: "Control total",
  feature2Desc: "Actualiza tu menú al instante desde cualquier lugar.",
  feature3Title: "Experiencia premium",
  feature3Desc: "Tus clientes amarán la interfaz rápida y moderna.",
  footerText: "Hecho en Panamá.",
};
